### ISSUE TITLE
how t7 file transform the image？ 

### ISSUE THREAD

**Issue by lt573152873** [ehsanik/SeGAN#2]
After th main.lua -weights_segmentation "weights/segment_gt_sv" -end2end -weights_texture "weights/texture_gt_sv" -istrain "test"，the output are t7 flies，how transform to image？

**Comment by ehsanik** [comment]
The t7 files are the snapshots of the model (including weights). If you want to visualize input and outputs, you can use command line commands as explained in `SettingsParser.lua` file.

**Comment by ehsanik** [comment]
The t7 files are the snapshots of the model (including weights). If you want to visualize input and outputs, you can use command line commands as explained in `SettingsParser.lua` file.
