### ISSUE TITLE
 How to visualize the end result?

### ISSUE THREAD

**Issue by lt573152873** [ehsanik/SeGAN#3]
th main.lua -weights_segmentation "weights/segment" -end2end -weights_texture "weights/texture" -istrain "test" -predictedSV

th main.lua -weights_segmentation "weights/segment_gt_sv" -end2end -weights_texture "weights/texture_gt_sv" -istrain "test"

Both of these commands will generate some t7 files. Are these files intermediate files?
So what parameters are added to the command to visualize the final result?

**Comment by changxinC** [comment]
Did you run through the model? Which version of lua is used? I used it for the first time and I didn't know how to solve it. In addition, do I need to download a 12G pre-training model to train my own data?

**Comment by ehsanik** [comment]
Yes these are the weights of the network that you can use to restart your training or do the inference. To visualize the results you can use `--vis_prob X`, where X is the probability that you pick an item to visualize. The visualization code happens [here](https://github.com/ehsanik/SeGAN/blob/d29e0a5ac08f093b87dc82af3707d50107900d04/networks/GANTextureNet.lua#L350).
