### ISSUE TITLE
I have a question --can't train

### ISSUE THREAD

**Issue by pyl62112991** [ehsanik/SeGAN#6]
![image](https://user-images.githubusercontent.com/47971541/59503551-43e78200-8ed3-11e9-9aac-a50b0c5a22f9.png)

thanks all

**Comment by ehsanik** [comment]
Make sure your model is loaded correctly. Are you training from scratch or finetuning on the previously trained models?

**Comment by pyl62112991** [comment]
>  finetuning on the previously trained models

i am  finetuning on the previously trained models

**Comment by ehsanik** [comment]
Can you provide more details? Such as the exact command you are running? Based on the limited information I get from the screenshot my guess is that either opt.which_model_netG is not set properly, resulting in netG being nil or the weights are not properly set.

**Comment by pyl62112991** [comment]
> Can you provide more details? Such as the exact command you are running? Based on the limited information I get from the screenshot my guess is that either opt.which_model_netG is not set properly, resulting in netG being nil or the weights are not properly set.

thank you i have solve the problem
