### ISSUE TITLE
cannot open <resnet-18.t7> in mode r

### ISSUE THREAD

**Issue by NaderahmadiD** [ehsanik/SeGAN#8]
Hello,

I'm trying to train the model with:

`th main.lua -baseLR 1e-3 -end2end -istrain "train"`

And I got this error:

`WARNING: specified initialized model is ignored because resnet model will be loaded!    
/home/darya/distro/install/bin/luajit: cannot open <resnet-18.t7> in mode r  at /home/darya/distro/pkg/torch/lib/TH/THDiskFile.c:673
stack traceback:
    [C]: at 0x7f6f3df5e210
    [C]: in function 'DiskFile'
    /home/darya/distro/install/share/lua/5.1/torch/File.lua:405: in function 'load'
    /home/darya/SeGAN/networks/ModelTrainTestBatch.lua:285: in function 'LoadModel'
    main.lua:293: in main chunk
    [C]: in function 'dofile'
    ...rya/distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
    [C]: at 0x55fcae37f570
`

Any help would be appreciated.

**Comment by ehsanik** [comment]
Hi,

This is just a warning, which is due to the code not being able to find the file "resnet-18.t7". If the code crashes, then there should be a problem somewhere else and this is not an error.
